<a href="https://colab.research.google.com/github/GarvitPro/data-science-numpy-panda-solutions/blob/main/DS27JanRegNo08AQ2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NumPy Basics – Arrays, Dimensions, Arange, Shape, Size & Reshape
import numpy as np
## 1. Creating a NumPy Array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
## 2. Checking Number of Dimensions using ndim
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("2D Array:")
print(arr2)
print("Number of dimensions:", arr2.ndim)
## 3. Generating Values using arange() from 12 to 50 with step 3
arr3 = np.arange(12, 51, 3)
print(arr3)
## 4. Shape and Size of a 2D Array
print("Shape of array:", arr2.shape)
print("Size of array:", arr2.size)
## 5. Reshaping 1D Array from 15 to 30
arr4 = np.arange(15, 31)
print("Original 1D array:")
print(arr4)

reshaped_arr = arr4.reshape(4, 4)
print("\nReshaped 2D array:")
print(reshaped_arr)


1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
Number of dimensions: 2
[12 15 18 21 24 27 30 33 36 39 42 45 48]
Shape of array: (2, 3)
Size of array: 6
Original 1D array:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]

Reshaped 2D array:
[[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]
